# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: glimmer-libui-cc-graphs_and_charts 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "glimmer-libui-cc-graphs_and_charts".freeze
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andy Maleh".freeze]
  s.date = "2023-12-16"
  s.description = "Graphs And Charts - Glimmer DSL for LibUI Custom Controls".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "glimmer-libui-cc-graphs_and_charts.gemspec",
    "lib/glimmer-libui-cc-graphs_and_charts.rb",
    "lib/glimmer/view/line_graph.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/glimmer-libui-cc-graphs_and_charts".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.6".freeze
  s.summary = "Graphs And Charts - Glimmer DSL for LibUI Custom Controls".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<glimmer-dsl-libui>.freeze, ["~> 0.11"])
  s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
  s.add_development_dependency(%q<juwelier>.freeze, ["= 2.4.9"])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
end

